import { OFFICIAL_PAUTAS } from "@/lib/officialPautas";

export type OfficialProjectCard = { card: number; headline: string; body: string; cta?: string };
export type OfficialProjectSeed = { project_id: string; template: string; title: string; caption: string; cta: string; cards: OfficialProjectCard[] };

const CTA = "Salve este conteúdo e envie para uma mulher que também está repensando o próprio cabelo.";

const COPY: Record<string, { template: string; caption: string; cards: Array<[string,string,string?]> }> = {
"CM-037":{template:"T01",caption:"Fios finos não precisam ser sinônimo de cabelo sem presença. O desenho do corte pode distribuir melhor o volume e devolver movimento sem exigir uma rotina impossível.",cards:[["Fios finos e pouco volume?","Antes de procurar mais um produto, observe o desenho do corte. Peso concentrado nas pontas pode deixar a raiz ainda mais sem presença."],["Nem sempre falta cabelo","Comprimento, base muito compacta e camadas mal posicionadas podem fazer fios finos parecerem ainda mais ralos."],["O corte pode trabalhar a seu favor","Camadas estratégicas, contorno leve e uma base bem escolhida criam movimento sem retirar densidade onde você mais precisa."],["Três caminhos possíveis","Bob com textura, médio em camadas suaves ou longo com face-framing. A escolha depende da densidade, textura e rotina — não da idade."],["Volume com naturalidade","O objetivo não é fabricar um cabelo que você não tem. É valorizar melhor o cabelo que já existe.","Comente “VOLUME” se você quer uma avaliação do seu corte."]]},
"CM-038":{template:"T08",caption:"Cabelo fino não precisa de uma prateleira inteira. Precisa de escolhas compatíveis com densidade, textura e rotina.",cards:[["Mais produto não significa mais volume","Excesso de creme, óleo ou máscara pode pesar justamente o fio que você quer ver mais solto." ]]},
"CM-039":{template:"T04",caption:"Assumir os brancos não precisa acontecer de uma vez. É possível construir uma transição elegante, gradual e coerente com você.",cards:[["Assumir os brancos pode ser mais leve","Você não precisa escolher entre cobrir tudo ou abandonar a cor de uma vez."],["Comece pelo contraste","Quando a diferença entre raiz branca e comprimento é muito grande, a manutenção parece mais pesada."],["A transição pode ser desenhada","Luzes finas, tonalização e ajustes de base podem suavizar a marcação enquanto os fios naturais crescem."],["Seu branco também tem identidade","Distribuição, porcentagem de brancos, tom de pele e corte mudam completamente o resultado."],["Não existe uma idade certa","Existe o momento em que você quer menos obrigação e mais coerência com a própria imagem.","Salve para conversar sobre sua transição na próxima visita."]]},
"CM-040":{template:"T02",caption:"Às vezes o corte não ficou ruim: sua rotina mudou. Um bom desenho precisa continuar funcionando quando você volta para casa.",cards:[["Seu corte perdeu o formato — ou sua rotina mudou?","Se o cabelo só funciona com a finalização do salão, talvez seja hora de rever comprimento, peso e manutenção." ]]},
"CM-041":{template:"T04",caption:"Uma iluminação bonita não apaga sua base: conversa com ela. Contraste, temperatura e distribuição precisam trabalhar juntos.",cards:[["A iluminação precisa conversar com a sua base","Morena iluminada não é simplesmente colocar mechas claras sobre um cabelo escuro."],["Sua base é parte do resultado","Castanho, preto, grisalho ou colorido mudam a leitura das mechas e o nível de contraste."],["Temperatura também importa","Mel, caramelo, bege ou avelã criam efeitos diferentes na pele e no cabelo."],["Menos contraste pode dar mais sofisticação","Uma iluminação bem distribuída cresce de forma mais suave e costuma exigir menos correção visual."],["Iluminar sem apagar você","A melhor cor preserva identidade e acrescenta dimensão.","Comente “LUZ” se você quer descobrir qual direção combina com sua base."]]},
"CM-042":{template:"T08",caption:"Frizz pode aparecer por ressecamento, dano, umidade, atrito ou simplesmente pela textura natural. Tratar tudo como falta de produto costuma piorar o diagnóstico.",cards:[["Frizz não é sempre falta de produto","Antes de adicionar mais creme, descubra se o fio pede hidratação, reconstrução, menos atrito ou apenas outra finalização." ]]},
"CM-043":{template:"T10",caption:"Cabelo curto não precisa apagar sua identidade. Existem muitos caminhos entre manter o comprimento e fazer uma mudança radical.",cards:[["Cortar curto não precisa significar virar outra pessoa","O curto certo preserva traços seus enquanto muda proporção e movimento."],["Comece pelo que você quer manter","Franja, volume, nuca coberta, cachos ou possibilidade de prender são pistas importantes."],["Short bob","Mantém uma leitura elegante e permite bastante variação de textura."],["Bixie e pixie alongado","Trazem leveza sem obrigar você a ir direto para um corte extremamente curto."],["Curto é uma família, não um corte","Escolha pela sua textura, rosto e rotina.","Salve suas referências favoritas antes da avaliação."]]},
"CM-044":{template:"T08",caption:"Fio fragilizado pede prioridade, não excesso de procedimentos. Em alguns momentos, preservar é o tratamento mais inteligente.",cards:[["Quando o cabelo está frágil, fazer mais pode não ser a resposta","Elasticidade, quebra e aspereza pedem diagnóstico antes de nova química, calor ou sobreposição de produtos." ]]},
"CM-045":{template:"T04",caption:"Se a raiz incomoda poucos dias depois da coloração, talvez o problema não seja a velocidade de crescimento — e sim a estratégia escolhida.",cards:[["A raiz aparece rápido?","Talvez a estratégia de cor precise mudar."],["Contraste alto denuncia crescimento","Quanto maior a distância entre sua base natural e a cor escolhida, mais cedo a raiz chama atenção."],["Nem toda cobertura precisa ser total","Esfumado, tonalização e técnicas de baixa marcação podem reduzir a sensação de linha rígida."],["Pense no intervalo entre visitas","Uma cor bonita também precisa continuar bonita durante o crescimento."],["Cor boa cabe na rotina","Escolha o efeito junto com a manutenção que você realmente consegue sustentar.","Salve para rever antes do próximo retoque."]]},
"CM-046":{template:"T02",caption:"O teste de um bom corte começa depois que você sai do salão. Ele precisa conversar com seu tempo, sua textura e sua habilidade de finalizar.",cards:[["O melhor corte não é o mais bonito no salão","É aquele que continua fazendo sentido em casa, nos dias comuns." ]]},
"CM-047":{template:"T04",caption:"Cachos podem ganhar luz preservando profundidade, desenho e presença. A distribuição da iluminação precisa respeitar a forma do cacho.",cards:[["Cachos também podem ganhar luz","Sem perder presença, profundidade ou leitura da textura."],["A mecha acompanha o desenho","A posição da luz muda conforme curvatura, volume e onde o cacho costuma abrir."],["Contraste controlado","Tons mel, caramelo e dourados podem criar dimensão sem transformar todo o cabelo em uma massa clara."],["Saúde vem antes da pressa","Cabelo cacheado sensibilizado exige avaliação antes de clarear."],["Luz para revelar textura","Não para apagar a base.","Comente “CACHOS” se essa é a mudança que você está pensando."]]},
"CM-048":{template:"T08",caption:"O cabelo muda com o tempo, com química, hormônios, rotina e ambiente. Continuar repetindo exatamente os mesmos cuidados pode deixar de funcionar.",cards:[["Depois de um tempo, o cabelo pode pedir outra rotina","Observe textura, quebra, oleosidade, ressecamento e resposta aos produtos antes de repetir o que sempre funcionou." ]]},
"CM-049":{template:"T01",caption:"Movimento não depende apenas de fazer camadas. Depende de onde o peso fica e de como o corte conversa com a densidade real do cabelo.",cards:[["Seu cabelo está sem movimento?","Talvez o problema seja a distribuição do peso."],["Camada demais também pode esvaziar","Em fios finos, retirar peso no lugar errado reduz densidade visual."],["Camada de menos pode endurecer","Em cabelos densos, uma massa única pode impedir balanço e desenho."],["O ponto certo é individual","Comprimento, curvatura, densidade e hábito de finalizar definem onde criar movimento."],["Movimento sem perder identidade","O corte deve facilitar o cabelo — não obrigar você a lutar com ele.","Salve e leve esta ideia para sua próxima avaliação."]]},
"CM-050":{template:"T08",caption:"Definição bonita não precisa virar capacete. Controle e movimento podem coexistir quando produto, quantidade e técnica estão equilibrados.",cards:[["Definição não precisa deixar o cabelo rígido","Menos produto, aplicação bem distribuída e finalização compatível com a curvatura podem preservar toque e movimento." ]]},
"CM-051":{template:"T04",caption:"Cobrir os brancos é uma escolha estética, não uma obrigação. Você pode cobrir, suavizar, misturar ou assumir.",cards:[["Cobrir os brancos é uma escolha","Não uma obrigação."],["Cobertura total","Entrega uniformidade, mas normalmente pede retoques mais frequentes."],["Mistura de brancos","Luzes e tonalizações podem diminuir o contraste sem esconder tudo."],["Assumir gradualmente","A transição pode ser planejada para evitar uma divisão brusca entre raiz e comprimento."],["Escolha pela sua vida","Não pela regra de que mulher madura precisa esconder o branco.","Qual caminho faz mais sentido para você hoje?"]]},
"CM-052":{template:"T02",caption:"Mudança boa não precisa apagar sua história. Um corte pode atualizar proporções mantendo aquilo que você reconhece como seu.",cards:[["Mudar o cabelo não precisa mudar quem você é","Às vezes alguns centímetros, um novo contorno ou outra distribuição de volume já transformam a leitura." ]]},
"CM-053":{template:"T09",caption:"Uma cor pode ser tecnicamente bonita e ainda parecer pesada no rosto. Muitas vezes o que incomoda é o contraste, não a tonalidade isolada.",cards:[["Quando o problema não é a cor","É o contraste."],["Muito escuro perto do rosto","Pode criar uma moldura mais rígida do que você deseja."],["Claro demais também pode apagar","Sem profundidade, pele e cabelo podem perder definição entre si."],["Contraste pode ser desenhado","Face-framing, profundidade na raiz e pontos de luz reposicionam a atenção."],["Cor também é proporção","A pergunta não é só “qual tom?”, mas “onde ele deve aparecer?”.","Salve para observar isso nas suas próximas referências."]]},
"CM-054":{template:"T08",caption:"Maciez e brilho não são a mesma coisa. Se o cabelo está hidratado mas opaco, vale investigar superfície do fio, acúmulo e dano.",cards:[["Seu cabelo está hidratado, mas continua sem brilho?","Pode haver porosidade, acúmulo de resíduos ou cutícula irregular — não apenas falta de máscara." ]]},
"CM-055":{template:"T09",caption:"Copiar o corte de outra pessoa raramente copia o resultado. Formato do rosto, implantação, densidade, textura e proporções mudam tudo.",cards:[["Por que o mesmo corte fica diferente em cada mulher?","Porque cabelo não existe separado do rosto, da textura e da rotina."],["Formato do rosto é só o começo","Testa, mandíbula, pescoço e proporções influenciam o desenho."],["Densidade muda a silhueta","O mesmo comprimento pode parecer leve em um cabelo e pesado em outro."],["Textura muda o caimento","Liso, ondulado, cacheado e crespo ocupam espaço de formas diferentes."],["Referência é ponto de partida","O corte final precisa ser traduzido para você.","Traga referências — e deixe espaço para a adaptação profissional."]]},
"CM-056":{template:"T08",caption:"Fios delicados agradecem decisões cuidadosas antes mesmo do creme de pentear. Lavagem, desembaraço, calor e atrito fazem parte do tratamento.",cards:[["O cuidado com fios delicados começa antes da finalização","Temperatura da água, força ao desembaraçar e excesso de calor podem pesar mais do que o produto escolhido no final." ]]},
"CM-057":{template:"T04",caption:"A cor ideal não é apenas a que você ama no dia do salão. É a que você consegue manter sem transformar sua agenda em obrigação.",cards:[["A cor precisa caber na sua agenda","Antes de escolher o efeito, escolha também a manutenção."],["Alto contraste","Costuma mostrar crescimento mais cedo e pedir visitas mais frequentes."],["Baixa marcação","Técnicas esfumadas e iluminação estratégica podem crescer de forma mais suave."],["Considere tempo e orçamento","A melhor técnica é aquela que você consegue sustentar com tranquilidade."],["Beleza sem escravidão","Planeje a cor pensando também nos próximos 90 dias.","Salve antes de escolher sua próxima mudança."]]},
"CM-058":{template:"T02",caption:"Pixie cacheado não precisa significar perder textura. O desenho pode usar o volume natural como protagonista.",cards:[["Pixie cacheado: curto sem apagar a textura","Laterais, topo e contorno podem ser ajustados para preservar cachos, movimento e personalidade." ]]},
"CM-059":{template:"T04",caption:"Nem toda mudança de cor precisa anunciar uma transformação radical. Pequenos deslocamentos de tom e luz já podem renovar o rosto.",cards:[["Quer mudar a cor sem parecer outra pessoa?","Comece por mudanças de baixa ruptura."],["Ilumine pontos estratégicos","Rosto e comprimento podem ganhar dimensão sem clarear tudo."],["Mude a temperatura","Do castanho neutro ao avelã, mel ou mocha, pequenas diferenças alteram a percepção."],["Preserve profundidade","Manter parte da base ajuda a conservar identidade e facilita o crescimento."],["Renovar sem apagar","A melhor mudança ainda deve parecer sua.","Comente “COR” se você prefere transformações sutis."]]},
"CM-060":{template:"T08",caption:"Cor bonita depende de fio saudável. Manutenção de cor inclui proteção térmica, tratamento adequado e atenção à porosidade.",cards:[["Cuidar da cor também é cuidar do fio","Quando a fibra perde resistência e uniformidade, brilho, tonalidade e durabilidade da cor também sofrem." ]]},
"CM-061":{template:"T10",caption:"Existe um território enorme entre o cabelo médio e o pixie. O short bob pode ser exatamente esse meio-termo.",cards:[["Quer cortar curto sem chegar ao pixie?","Conheça comprimentos que renovam sem radicalizar."],["Short bob clássico","Base próxima ao queixo ou um pouco abaixo, com leitura limpa e elegante."],["Bob texturizado","Mais movimento e menos rigidez para quem gosta de acabamento natural."],["Bob com franja ou face-framing","Muda a moldura do rosto sem exigir uma nuca extremamente curta."],["Curto na sua medida","Defina primeiro o que você não quer perder: textura, possibilidade de prender ou cobertura da nuca.","Salve as opções que mais combinam com você."]]},
"CM-062":{template:"T08",caption:"Rotina perfeita que você não consegue cumprir não é perfeita. Cuidado bom precisa caber no seu tempo e no seu orçamento.",cards:[["O melhor cuidado é o que cabe na sua vida","Poucos passos bem escolhidos e repetidos com constância costumam valer mais que uma rotina enorme abandonada em duas semanas." ]]},
"CM-063":{template:"T04",caption:"A manutenção da cor começa no dia em que você sai do salão. Hábitos em casa influenciam brilho, desbotamento e resistência do fio.",cards:[["A manutenção da cor começa antes da próxima visita","O que você faz em casa interfere diretamente no resultado."],["Calor sem proteção cobra preço","Secador e prancha em excesso aceleram ressecamento e perda de brilho."],["Lavagem também importa","Frequência, temperatura e produtos inadequados podem acelerar o desbotamento."],["Trate de acordo com o fio","Coloração não elimina a necessidade de equilibrar hidratação, nutrição e reconstrução."],["Faça a cor durar melhor","Manutenção inteligente preserva aparência e saúde.","Salve este checklist para sua rotina."]]},
"CM-064":{template:"T02",caption:"Bixie fica entre bob e pixie: mais forma e leveza sem necessariamente expor tanto a nuca ou reduzir demais o comprimento.",cards:[["Bixie: mais forma sem radicalizar","Uma alternativa para quem quer sair do médio e experimentar um curto ainda versátil." ]]},
"CM-065":{template:"T04",caption:"Iluminar não significa transformar todo o cabelo em loiro. Profundidade preservada pode deixar a cor mais rica e a manutenção mais confortável.",cards:[["Iluminar sem apagar sua base","Sua cor natural pode continuar sendo protagonista."],["Profundidade cria dimensão","Manter áreas escuras faz os pontos claros aparecerem com mais intenção."],["Luz não precisa começar na raiz","Distribuição mais suave reduz marcação durante o crescimento."],["Escolha tons que conversem","Mel, caramelo, avelã, bege ou bronde podem iluminar mantendo leitura de morena."],["Sua base também é bonita","Iluminação deve acrescentar, não substituir.","Salve se você quer clarear sem deixar de se reconhecer."]]},
"CM-066":{template:"T08",caption:"O cabelo da sua amiga pode amar uma rotina que pesa no seu. Diagnóstico individual vale mais que copiar uma lista de produtos.",cards:[["Seu cabelo não precisa seguir a rotina de outra pessoa","Curvatura, densidade, química, porosidade, couro cabeludo e hábitos mudam o que funciona para cada mulher." ]]}
};

export const OFFICIAL_PROJECTS: OfficialProjectSeed[] = OFFICIAL_PAUTAS.map((pauta) => {
  const copy = COPY[pauta.id];
  if (!copy) throw new Error(`copy_missing:${pauta.id}`);
  return {
    project_id: pauta.id,
    template: copy.template,
    title: pauta.title,
    caption: copy.caption,
    cta: CTA,
    cards: copy.cards.map(([headline, body, cta], index) => ({ card: index + 1, headline, body, ...(cta ? { cta } : {}) })),
  };
});
